spring:
  profiles:
    active: dev

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    web-example:
      write:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/web_example?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
        username: root
        password: 123456
      read:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/web_example?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
        username: root
        password: 123456

  redis:
    host: 10.198.25.10
    pool: 6379

endpoints:
  default:
    web:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

security:
  oauth2:
    client:
      clientId: WEB-EXAMPLE
      clientSecret: "secret"
      tokenEndpointUrl: http://AUTH-EXAMPLE/oauth/token
    resource:
      token-info-uri: http://AUTH-EXAMPLE/oauth/check_token

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8888/eureka/

logging:
  level:
    pers.xiaomuma.example: debug
